import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  // console.log(props, "parents modal 123");
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {props.children}
          {props.parallel}
        </main>
      </body>
    </html>
  );
}
